name: generate contribution snake

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: aryanyaksh-art
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%237c3aed&color_dots=%23ebedf0,%23ddd6fe,%23c4b5fd,%23a78bfa,%237c3aed
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23a78bfa&color_dots=%2321262d,%234c1d95,%236d28d9,%238b5cf6,%23c4b5fd

      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          directory: dist
          force: true
